version: '2.4'
services:
  postgres:
    image: postgres:14
    container_name: md_postgres
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./postgres/:/docker-entrypoint-initdb.d/
      - ./markdown/:/markdown/
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'
      POSTGRES_PASSWORD: 'password'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 25